name: 🔧 Manual Deploy to VPS

on:
  workflow_dispatch:  # 🧠 Only runs when triggered manually in the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🚀 Do something
      run: echo "This job was triggered manually"